import { engStats, playerPostion, postion } from "./alltype";

export const defaultSeasons: Array<string> = [
  "icon",
  "nhd",
  "tki",
  "tb",
  "tt",
  "gr",
  "19toty",
  "18toty",
  "mcicon",
  "tc",
  "19tots",
  "hot",
  "coc",
  "otw",
  "19ng",
  "20toty",
  "19ucl",
  "20totn",
  "tkl",
  "20tots",
  "vtr",
  "mog",
  "lh",
  "la",
  "mc",
  "20ng",
  "20klb",
  "21toty",
  "21totn",
  "20ucl",
  "up",
  "2012kh",
  "ngt",
  "21tots",
  "ebs",
  "cap",
  "boe21",
  "cfa",
  "btb",
  "21klb",
  "22toty",
  "22totn",
  "21ucl",
  "22hr",
  "21ng",
  "fa",
  "lol",
  "22tots",
  "ln",
  "spl",
  "bwc",
  "wc22",
  "rmcf",
  "22ng",
  "22klb",
  "23toty",
  "23totn",
  "22ucl",
  "23hr",
  "hg",
  "rtn",
  "22kfa",
  "21kfa",
  "2019kfa",
  "mcfc",
  "kfa",
  "live",
  "17",
  "18",
  "19",
  "20",
  "21",
  "plc",
  "18pls",
  "19pla",
  "19pls",
  "20kl",
  "20pla",
  "21kl",
  "21pla",
  "22kl",
  "22pla",
];

export const defaultPostions: Array<postion> = [
  "st",
  "ls",
  "rs",
  "cf",
  "lf",
  "rf",
  "lw",
  "rw",
  "cm",
  "lcm",
  "rcm",
  "cam",
  "lam",
  "ram",
  "cdm",
  "ldm",
  "rdm",
  "lm",
  "rm",
  "cb",
  "lcb",
  "rcb",
  "lb",
  "rb",
  "lwb",
  "rwb",
  "sw",
  "gk",
];

export const defaultPlayerPostions: Array<playerPostion> = [
  "ST",
  "CF",
  "LF",
  "RF",
  "LW",
  "RW",
  "CM",
  "CAM",
  "CDM",
  "LM",
  "RM",
  "CB",
  "LB",
  "RB",
  "LWB",
  "RWB",
  "SW",
  "GK",
];

export const defaultPhysicals: Array<string> = [
  "건장",
  "보통",
  "마름",
  "건장(고유)",
  "보통(고유)",
  "마름(고유)",
];

export const defaultMainFoots: Array<string> = ["L5", "R5"];

export const defaultTraits: Array<{ id: number; name: string }> = [
  { id: 1, name: "화려한 걷어내기" },
  { id: 2, name: "트러블 메이커" },
  { id: 3, name: "주발 선호" },
  { id: 6, name: "다이버" },
  { id: 7, name: "슬라이딩 태클 선호" },
  { id: 8, name: "얼리 크로스 선호" },
  { id: 10, name: "예리한 감아차기" },
  { id: 11, name: "화려한 개인기" },
  { id: 12, name: "초 장거리 스로인" },
  { id: 13, name: "GK 소극적 크로스 수비" },
  { id: 14, name: "GK 적극적 크로스 수비" },
  { id: 15, name: "GK 멀리 던지기" },
  { id: 16, name: "GK 침착한 1:1 수비" },
  { id: 17, name: "선호포지션 고집" },
  { id: 18, name: "유리몸" },
  { id: 20, name: "긴 패스 선호" },
  { id: 21, name: "중거리 슛 선호" },
  { id: 22, name: "장거리 스로인" },
  { id: 24, name: "아웃사이드 슈팅/크로스" },
  { id: 25, name: "플레이 메이커" },
  { id: 26, name: "파워 헤더" },
  { id: 27, name: "GK 능숙한 펀칭" },
  { id: 28, name: "GK 공격 가담" },
  { id: 29, name: "승부욕" },
  { id: 30, name: "개인 플레이 선호" },
  { id: 31, name: "칩슛 선호" },
  { id: 32, name: "강철몸" },
  { id: 33, name: "스피드 드리블러" },
  { id: 34, name: "스위퍼 키퍼" },
  { id: 35, name: "패스 마스터" },
  { id: 39, name: "테크니컬 드리블러" },
];

export const defaultSkillMoves: Array<{ id: number; name: string }> = [
  { id: 0, name: "" },
  { id: 5, name: "★★★★★" },
  { id: 4, name: "★★★★" },
  { id: 3, name: "★★★" },
  { id: 2, name: "★★" },
  { id: 1, name: "★" },
];

export const defaultSubFoots: Array<{ id: number; name: string }> = [
  { id: 0, name: "" },
  { id: 5, name: "5" },
  { id: 4, name: "4" },
  { id: 3, name: "3" },
  { id: 2, name: "2" },
  { id: 1, name: "1" },
];

export const defaultStatsList: Array<{
  id: number;
  name: string;
  engName: engStats;
}> = [
  { id: 1, name: "속력", engName: "sprintspeed" },
  { id: 2, name: "가속력", engName: "acceleration" },
  { id: 3, name: "골 결정력", engName: "finishing" },
  { id: 4, name: "슛 파워", engName: "shotpower" },
  { id: 5, name: "중거리 슛", engName: "longshots" },
  { id: 6, name: "위치 선정", engName: "positioning" },
  { id: 7, name: "발리슛", engName: "volleys" },
  { id: 8, name: "페널티 킥", engName: "penalties" },
  { id: 9, name: "짧은 패스", engName: "shortpassing" },
  { id: 10, name: "시야", engName: "vision" },
  { id: 11, name: "크로스", engName: "crossing" },
  { id: 12, name: "긴 패스", engName: "longpassing" },
  { id: 13, name: "프리킥", engName: "freekickaccuracy" },
  { id: 14, name: "커브", engName: "curve" },
  { id: 15, name: "드리블", engName: "dribbling" },
  { id: 16, name: "볼 컨트롤", engName: "ballcontrol" },
  { id: 17, name: "민첩성", engName: "agility" },
  { id: 18, name: "밸런스", engName: "balance" },
  { id: 19, name: "반응 속도", engName: "reactions" },
  { id: 20, name: "대인 수비", engName: "marking" },
  { id: 21, name: "태클", engName: "standingtackle" },
  { id: 22, name: "가로채기", engName: "interceptions" },
  { id: 23, name: "헤더", engName: "headingaccuracy" },
  { id: 24, name: "슬라이딩 태클", engName: "slidingtackle" },
  { id: 25, name: "몸싸움", engName: "strength" },
  { id: 26, name: "스태미너", engName: "stamina" },
  { id: 27, name: "적극성", engName: "aggression" },
  { id: 28, name: "점프", engName: "jumping" },
  { id: 29, name: "침착성", engName: "composure" },
  { id: 30, name: "GK 다이빙", engName: "gkdiving" },
  { id: 31, name: "GK 핸들링", engName: "gkhandling" },
  { id: 32, name: "GK 킥", engName: "gkkicking" },
  { id: 33, name: "GK 반응속도", engName: "gkreflexes" },
  { id: 34, name: "GK 위치 선정", engName: "gkpositioning" },
  { id: 35, name: "키", engName: "height" },
  { id: 36, name: "몸무게", engName: "weight" },
  { id: 37, name: "급여", engName: "pay" },
];

export const defaultStats: Map<engStats, string> = new Map([
  ["sprintspeed", "속력"],
  ["acceleration", "가속력"],
  ["finishing", "골 결정력"],
  ["shotpower", "슛 파워"],
  ["longshots", "중거리 슛"],
  ["positioning", "위치 선정"],
  ["volleys", "발리슛"],
  ["penalties", "페널티 킥"],
  ["shortpassing", "짧은 패스"],
  ["vision", "시야"],
  ["crossing", "크로스"],
  ["longpassing", "긴 패스"],
  ["freekickaccuracy", "프리킥"],
  ["curve", "커브"],
  ["dribbling", "드리블"],
  ["ballcontrol", "볼 컨트롤"],
  ["agility", "민첩성"],
  ["balance", "밸런스"],
  ["reactions", "반응 속도"],
  ["marking", "대인 수비"],
  ["standingtackle", "태클"],
  ["interceptions", "가로채기"],
  ["headingaccuracy", "헤더"],
  ["slidingtackle", "슬라이딩 태클"],
  ["strength", "몸싸움"],
  ["stamina", "스태미너"],
  ["aggression", "적극성"],
  ["jumping", "점프"],
  ["composure", "침착성"],
  ["gkdiving", "GK 다이빙"],
  ["gkhandling", "GK 핸들링"],
  ["gkkicking", "GK 킥"],
  ["gkreflexes", "GK 반응속도"],
  ["gkpositioning", "GK 위치 선정"],
]);
